### ISSUE TITLE
现象是将插件放到plugins中mirai并不会加载这个插件，我是在actions中下载的jar文件

### ISSUE THREAD

**Issue by HuaWaterED** [ryoii/mirai-rate-limit#1]
mirai版本2.15.0
除了mirai-rate-limit插件外，其他插件信息如下：
chat-command-0.6.0
fix-protocol-version-1.9.11
mcl-addon-2.1.1
mirai-api-http-2.9.1
mirai-login-solver-sakura-0.0.12
onebot-mirai-0.3.4
qsign-1.0.7

**Comment by ryoii** [comment]
action的压缩包应该解压后才是插件的jar包，我重新修复了一些问题

**Comment by happpybob** [comment]
> action的压缩包应该解压后才是插件的jar包，我重新修复了一些问题

所以这个问题是怎么解决的呢，现在把jar文件放进去还是无法加载
